Update README.md
openapi-contrib/glossary pull request #4
Opened 2019-12-10 13:51 UTC by matthewtrask

added a `converters` definition since that one always confused me :)

2019-12-10 14:04 UTC, philsturgeon commented on README.md
> +A set of tools that allow you to convert the OpenAPI Specification file to another API format such as API Blueprint, HAR, RAML, and others. Certain convereter tools also let you convert your API docu
```suggestion
A set of tools that allow you to convert OpenAPI descriptions to another description format, such as API Blueprint, HAR, RAML, etc., or vice versa! Some will also convert to HTML which is usually for making [reference documentation](#reference-documentation).
```

2019-12-10 14:04 UTC, philsturgeon requested changes

2019-12-10 14:04 UTC, philsturgeon commented on README.md
> +A set of tools that allow you to convert the OpenAPI Specification file to another API format such as API Blueprint, HAR, RAML, and others. Certain convereter tools also let you convert your API docu
How's about this @matthewtrask

2019-12-20 01:43 UTC, matthewtrask commented
@philsturgeon that looks good!

2019-12-20 01:43 UTC, matthewtrask commented
just committed it up, so this should be good @philsturgeon

2019-12-20 07:57 UTC, cebe approved these changes

2019-12-20 10:29 UTC, philsturgeon approved these changes

2019-12-20 10:29 UTC, merged